version: '3.9'

services:
  server:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123!?
      - MYSQL_DATABASE=diesel_demo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

volumes:
  mysql-data:
